# 逻辑回归 Logistic Regression

## 分类问题 Classification 
结果是有限的就是分类问题

z = w1*x1+....
Sigmoid Function = 1/(1+e**(-z)) 这就是逻辑回归的模型

In [1]:
#导入数据
import pandas as pd
url = "Diabetes_Data.csv"
data = pd.read_csv(url)
data 

Age  Weight  BloodSugar Gender  Diabetes
0     25     119       130.8     男生         1
1     66     102       128.1     女生         1
2     59      65       103.9     男生         0
3     46     117        94.8     女生         0
4     45      79        57.8     男生         0
..   ...     ...         ...    ...       ...
395   72      63        97.1     女生         0
396   22     117       156.7     女生         1
397   31      76       119.0     男生         0
398   36      65        96.3     女生         1
399   38      75       106.3     男生         0

[400 rows x 5 columns]

In [2]:
#资料处理
data['Gender'] =  data["Gender"].map({"男生":1 , "女生": 0 })
data

Age  Weight  BloodSugar  Gender  Diabetes
0     25     119       130.8       1         1
1     66     102       128.1       0         1
2     59      65       103.9       1         0
3     46     117        94.8       0         0
4     45      79        57.8       1         0
..   ...     ...         ...     ...       ...
395   72      63        97.1       0         0
396   22     117       156.7       0         1
397   31      76       119.0       1         0
398   36      65        96.3       0         1
399   38      75       106.3       1         0

[400 rows x 5 columns]

In [ ]:
#训练集和测试集
#资料预处理 ：训练集，测试集
y = data["Diabetes"]
x = data[["Age" ,"Weight","BloodSugar","Gender"]]
#分成测试和训练
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2,random_state=87)

#转换成numpy,方便计算
x_train = x_train.to_numpy()
y_train = y_train.to_numpy()
x_test = x_test.to_numpy()
y_test = y_test.to_numpy()


array([[ 47. ,  78. , 112.7,   1. ],
       [ 41. ,  79. ,  90.5,   1. ],
       [ 28. ,  74. ,  96.4,   0. ],
       ...,
       [ 44. ,  53. , 122.2,   1. ],
       [ 42. ,  47. ,  69.7,   1. ],
       [ 69. , 101. ,  97. ,   0. ]])

In [ ]:
#特征缩放 Feature Scaling  可以加速gradient_descent 
# 标准化 standardization
# x-mean(x)
# ---------
# x标准差

#用库函数来做标准化
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
#直接用训练集的标准差和平均值来标准化测试集合
x_test = scaler.transform(x_test)


array([[-0.13049114, -0.12021965,  0.35271768,  0.93933644],
       [-0.49202504, -0.07737968, -0.61346817,  0.93933644],
       [-1.27534849, -0.2915795 , -0.35668905, -1.06458129],
       ...,
       [-0.31125809, -1.19121871,  0.76617559,  0.93933644],
       [-0.43176939, -1.44825849, -1.51872338,  0.93933644],
       [ 1.19513315,  0.8650995 , -0.33057592, -1.06458129]])

In [11]:
import numpy as np
def sigmoid(z):
    return  1/(1+np.exp(-z))
    

In [ ]:

w  = np.array([1,2,3,4])
b = 1 
z  = (w*x_train).sum(axis=1)+b
sigmoid(z)

array([9.95698875e-01, 9.06375097e-01, 2.05197222e-03, 9.99871937e-01,
       9.99976601e-01, 9.99597573e-01, 9.42501826e-03, 6.58750315e-01,
       9.72220502e-01, 2.04535575e-03, 9.95406153e-01, 9.33440694e-01,
       9.99020890e-01, 6.88676986e-03, 8.77843224e-05, 7.26538573e-01,
       9.32368144e-01, 8.09433980e-02, 1.22884071e-02, 6.59095116e-01,
       9.35714906e-01, 6.38508320e-02, 3.04389233e-01, 9.30273981e-01,
       1.23897708e-03, 9.93625786e-01, 5.90053392e-02, 9.86068856e-01,
       1.89102010e-04, 1.33090984e-03, 8.85296779e-01, 9.99482973e-01,
       4.70219520e-04, 9.99353194e-01, 1.87660501e-01, 9.95430646e-01,
       9.98245826e-01, 9.99905804e-01, 9.77808458e-01, 4.92634254e-03,
       9.98319405e-01, 9.99759816e-01, 1.56719013e-01, 4.11932567e-01,
       1.47183312e-01, 8.92262698e-01, 9.92187079e-01, 1.02910854e-01,
       8.61895492e-01, 5.88617508e-02, 9.36987924e-02, 3.51332925e-01,
       9.22153819e-01, 2.12994568e-02, 6.66132695e-01, 9.13035739e-01,
      